sudo: required
services:
  - docker

before_install:
  - docker build -t nicolajniels1/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true nicolajniels1/docker-react npm run test --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-eu-west-1-448228532605"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
